<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\RetailFlow.Application\RetailFlow.Application.csproj" />
    <ProjectReference Include="..\..\src\RetailFlow.Infrastructure\RetailFlow.Infrastructure.csproj" />
  </ItemGroup>

</Project>
